version: '3.8'
services:
  backend:
    build:
      context: softnix-api/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    container_name: suftnix-api
    environment:
     - NODE_ENV=production
    depends_on:
      - frontend

  frontend:
    build:
      context: softnix-ui/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    container_name: suftnix-ui
    environment:
     - NODE_ENV=production