version: '3.8'
services:
  backend:
    build:
      context: ./softnix-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./softnix-api:/app
      - /app/node_modules
    environment:
     - NODE_ENV=production

  frontend:
    build:
      context: ./softnix-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./softnix-ui:/app
      - /app/node_modules
    environment:
     - NODE_ENV=production