version: '3.8'
services:
  backend:
    build:
      context: softnix-api/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: suftnix-api
    environment:
     - NODE_ENV=production
    networks:
      - softnix-network

  frontend:
    build:
      context: softnix-ui/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    container_name: suftnix-ui
    environment:
     - NODE_ENV=production
    networks:
      - softnix-network

networks:
  softnix-network:
    driver: bridge